#ifndef SPRINTATHON_ZPC_IMPORT_FILES_H
#define SPRINTATHON_ZPC_IMPORT_FILES_H
// Filesystem adapter for the experimental importer. GPL-3.0-or-later.
#include "zpc_import.h"
#include "FileHandler.h"
#include <fstream>
#include <sstream>
#include <iomanip>

namespace zpc_import {
inline Bytes read_file(const FileSpecifier& path) {
    std::ifstream f(path.GetPath(),std::ios::binary|std::ios::ate);
    require(bool(f),std::string("cannot open ")+path.GetPath());
    auto n=f.tellg();
    require(n>=0 && n<=64*1024*1024,std::string("invalid file size: ")+path.GetPath());
    Bytes b(static_cast<size_t>(n)); f.seekg(0);
    if(!b.empty()) f.read(reinterpret_cast<char*>(b.data()),b.size());
    require(bool(f),std::string("cannot read ")+path.GetPath()); return b;
}
inline Bytes find_file(const FileSpecifier& dir,std::initializer_list<const char*> names) {
    for(auto name:names) { auto p=dir+name; if(p.Exists() && !p.IsDir()) return read_file(p); }
    throw std::runtime_error(std::string("ZPC import: missing ")+*names.begin()+" in "+dir.GetPath());
}
inline void write_file(const FileSpecifier& path,const Bytes& b) {
    auto existing=path;
    if(existing.Exists() && read_file(existing)==b) return;
    std::ofstream f(path.GetPath(),std::ios::binary|std::ios::trunc);
    require(bool(f),std::string("cannot create ")+path.GetPath());
    f.write(reinterpret_cast<const char*>(b.data()),b.size()); f.close();
    require(bool(f),std::string("cannot write ")+path.GetPath());
}
inline std::string prepare(const std::string& source,const std::string& support,const std::string& local) {
    require(!source.empty(),"supply the original ZPC directory after --zpc");
    require(!support.empty(),"supply --zpc-support with a Marathon 2 or ZPC-Preview directory");
    FileSpecifier src(source), base(support);
    auto original=find_file(src,{"ZPCshapes.shpA","zpcshapes.shpA","Shapes","Shapes.shpA"});
    auto map=find_file(src,{"zpcmap.sceA","ZPCmap.sceA","Map","Map.sceA"});
    auto landscape=find_file(src,{"landscap.lnd","LANDSCAP.LND"});
    auto base_shapes=find_file(base,{"Shapes","Shapes.shpA"});
    auto images=find_file(base,{"Images","Images.imgA"});
    auto menu=find_file(src,{"images.img","Images.imgA","Images","IMAGES.IMG"});
    require(get(menu,0,2)==2 && get(menu,80,2)==16 && get(menu,82,2)==10,
            "unsupported ZPC Images file");
    auto sounds=find_file(base,{"Sounds","Sounds.sndA"});
    // Build and validate before writing anything. Original files are never modified.
    auto displays=static_displays(original);
    auto converted_shapes=shapes(original,base_shapes,landscape,&displays);
    auto converted_map=maps(map,&displays);
    uint64_t hash=14695981039346656037ull;
    for(const auto* b:{&original,&map,&landscape,&base_shapes,&images,&sounds,&menu}) {
        for(auto c:*b) { hash^=c; hash*=1099511628211ull; }
        hash^=b->size(); hash*=1099511628211ull;
    }
    std::ostringstream id; id<<std::hex<<std::setw(16)<<std::setfill('0')<<hash;
    FileSpecifier root(local); root.MakeDirectory(); root+="ZPC-import-v3"; root.MakeDirectory();
    auto out=root+id.str(); out.MakeDirectory(); auto scripts=out+"Scripts"; scripts.MakeDirectory();
    write_file(out+"Shapes",converted_shapes); write_file(out+"Map",converted_map);
    write_file(out+"ZPC-Menu",menu);
    write_file(out+"Images",images); write_file(out+"Sounds",sounds);
    write_file(scripts+"ZPC.mml",bytes(mml()));
    write_file(out+"README.txt",bytes(
        "Generated by Sprintathon --zpc. Experimental exploration only.\n"
        "Original ZPC files are unchanged. Eight landscape assignments are inferred.\n"
        "Monsters and scenery are static, non-solid displays. Combat, items, liquids, terminals, panels and exits are disabled.\n"
        "Marathon support assets provide the player, interface and sounds.\n"
        "Console: .1 through .36 select a level; .next advances; .open opens platforms.\n"
        "Re-run the same command to regenerate these files.\n"));
    return out.GetPath();
}
}
#endif
